/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.gravatar.publicapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param searchEngines 
 */


data class EntryShareFlags (

    @SerializedName("search_engines")
    val searchEngines: kotlin.Boolean

)

