/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.gravatar.publicapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param photos 
 * @param lastProfileEdit 
 * @param hiddenAvatar 
 * @param hiddenContactInfo 
 * @param hiddenWallet 
 * @param profileBackground 
 * @param name 
 * @param displayName 
 * @param aboutMe 
 * @param currentLocation 
 * @param contactInfo 
 * @param emails 
 * @param accounts 
 * @param urls 
 * @param shareFlags 
 * @param age 
 */


data class EntryScoreFull (

    @SerializedName("photos")
    val photos: kotlin.Int,

    @SerializedName("last_profile_edit")
    val lastProfileEdit: kotlin.Int,

    @SerializedName("hidden_avatar")
    val hiddenAvatar: kotlin.Int,

    @SerializedName("hidden_contact_info")
    val hiddenContactInfo: kotlin.Int,

    @SerializedName("hidden_wallet")
    val hiddenWallet: kotlin.Int,

    @SerializedName("profileBackground")
    val profileBackground: kotlin.Int,

    @SerializedName("name")
    val name: kotlin.Int,

    @SerializedName("displayName")
    val displayName: kotlin.Int,

    @SerializedName("aboutMe")
    val aboutMe: kotlin.Int,

    @SerializedName("currentLocation")
    val currentLocation: kotlin.Int,

    @SerializedName("contactInfo")
    val contactInfo: kotlin.Int,

    @SerializedName("emails")
    val emails: kotlin.Int,

    @SerializedName("accounts")
    val accounts: kotlin.Int,

    @SerializedName("urls")
    val urls: kotlin.Int,

    @SerializedName("share_flags")
    val shareFlags: kotlin.Int,

    @SerializedName("age")
    val age: kotlin.Int

)

