/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.gravatar.publicapi.models

import com.gravatar.publicapi.models.EntryScoreAccountable
import com.gravatar.publicapi.models.EntryScoreFull

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `value` 
 * @param full 
 * @param accountable 
 */


data class EntryScore (

    @SerializedName("value")
    val `value`: kotlin.Int,

    @SerializedName("full")
    val full: EntryScoreFull,

    @SerializedName("accountable")
    val accountable: EntryScoreAccountable

)

