/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.gravatar.publicapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param profileBackground 
 * @param name 
 * @param displayName 
 * @param aboutMe 
 * @param currentLocation 
 * @param emails 
 * @param accounts 
 * @param urls 
 * @param age 
 */


data class EntryScoreAccountable (

    @SerializedName("profileBackground")
    val profileBackground: kotlin.Int,

    @SerializedName("name")
    val name: kotlin.Int,

    @SerializedName("displayName")
    val displayName: kotlin.Int,

    @SerializedName("aboutMe")
    val aboutMe: kotlin.Int,

    @SerializedName("currentLocation")
    val currentLocation: kotlin.Int,

    @SerializedName("emails")
    val emails: kotlin.Int,

    @SerializedName("accounts")
    val accounts: kotlin.Int,

    @SerializedName("urls")
    val urls: kotlin.Int,

    @SerializedName("age")
    val age: kotlin.Int

)

