/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.gravatar.publicapi.models

import com.gravatar.publicapi.models.EntryName
import com.gravatar.publicapi.models.EntryProfileBackground
import com.gravatar.publicapi.models.EntryScore
import com.gravatar.publicapi.models.EntryShareFlags

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param hash 
 * @param requestHash 
 * @param profileUrl 
 * @param preferredUsername 
 * @param thumbnailUrl 
 * @param lastProfileEdit 
 * @param profileBackground 
 * @param name 
 * @param displayName 
 * @param pronouns 
 * @param aboutMe 
 * @param currentLocation 
 * @param shareFlags 
 * @param score 
 */


data class Entry (

    @SerializedName("hash")
    val hash: kotlin.String,

    @SerializedName("requestHash")
    val requestHash: kotlin.String? = null,

    @SerializedName("profileUrl")
    val profileUrl: kotlin.String? = null,

    @SerializedName("preferredUsername")
    val preferredUsername: kotlin.String? = null,

    @SerializedName("thumbnailUrl")
    val thumbnailUrl: kotlin.String? = null,

    @SerializedName("last_profile_edit")
    val lastProfileEdit: kotlin.String? = null,

    @SerializedName("profileBackground")
    val profileBackground: EntryProfileBackground? = null,

    @SerializedName("name")
    val name: EntryName? = null,

    @SerializedName("displayName")
    val displayName: kotlin.String? = null,

    @SerializedName("pronouns")
    val pronouns: kotlin.String? = null,

    @SerializedName("aboutMe")
    val aboutMe: kotlin.String? = null,

    @SerializedName("currentLocation")
    val currentLocation: kotlin.String? = null,

    @SerializedName("share_flags")
    val shareFlags: EntryShareFlags? = null,

    @SerializedName("score")
    val score: EntryScore? = null

)

