/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.gravatar.publicapi.models

import com.gravatar.publicapi.models.Entry

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param entry 
 */


data class Profile (

    @SerializedName("entry")
    val entry: kotlin.collections.List<Entry>

)

