/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.restapi.apis

import com.gravatar.restapi.models.Identity
import com.gravatar.restapi.models.SelectAvatar
import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.Path

internal interface IdentitiesApi {
    /**
     * Get identity details
     * Retrieves details for the identity associated with the provided email hash.
     * Responses:
     *  - 200: Successful retrieval of identity details
     *
     * @param emailHash SHA256 hash of the email address
     * @return [Identity]
     */
    @GET("me/identities/{emailHash}")
    suspend fun getIdentity(
        @Path("emailHash") emailHash: kotlin.String,
    ): Response<Identity>

    /**
     * Set avatar for identity
     * Sets the avatar for the identity associated with the provided email hash.
     * Responses:
     *  - 204: Avatar successfully set
     *
     * @param emailHash SHA256 hash of the email address
     * @param selectAvatar Avatar selection details
     * @return [Unit]
     */
    @POST("me/identities/{emailHash}/avatar")
    suspend fun setIdentityAvatar(
        @Path("emailHash") emailHash: kotlin.String,
        @Body selectAvatar: SelectAvatar,
    ): Response<Unit>
}
