/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.restapi.models

import com.google.gson.annotations.SerializedName
import java.util.Objects

/**
 *
 *
 * @param associated Whether the email is associated with a Gravatar account.
 */

public class AssociatedEmail200Response private constructor(
    // Whether the email is associated with a Gravatar account.
    @SerializedName("associated")
    public val associated: kotlin.Boolean,
) {
    override fun toString(): String = "AssociatedEmail200Response(associated=$associated)"

    override fun equals(other: Any?): Boolean = other is AssociatedEmail200Response &&
        associated == other.associated

    override fun hashCode(): Int = Objects.hash(associated)

    public class Builder {
        // Whether the email is associated with a Gravatar account.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var associated: kotlin.Boolean? = null

        public fun setAssociated(associated: kotlin.Boolean?): Builder = apply { this.associated = associated }

        public fun build(): AssociatedEmail200Response = AssociatedEmail200Response(associated!!)
    }
}

@JvmSynthetic // Hide from Java callers who should use Builder.
public fun AssociatedEmail200Response(initializer: AssociatedEmail200Response.Builder.() -> Unit): AssociatedEmail200Response {
    return AssociatedEmail200Response.Builder().apply(initializer).build()
}
