/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.restapi.models

import com.google.gson.annotations.SerializedName
import java.util.Objects

/**
 * A gallery image a user has uploaded.
 *
 * @param url The URL to the image.
 */

public class GalleryImage private constructor(
    // The URL to the image.
    @SerializedName("url")
    public val url: java.net.URI,
) {
    override fun toString(): String = "GalleryImage(url=$url)"

    override fun equals(other: Any?): Boolean = other is GalleryImage &&
        url == other.url

    override fun hashCode(): Int = Objects.hash(url)

    public class Builder {
        // The URL to the image.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var url: java.net.URI? = null

        public fun setUrl(url: java.net.URI?): Builder = apply { this.url = url }

        public fun build(): GalleryImage = GalleryImage(url!!)
    }
}

@JvmSynthetic // Hide from Java callers who should use Builder.
public fun GalleryImage(initializer: GalleryImage.Builder.() -> Unit): GalleryImage {
    return GalleryImage.Builder().apply(initializer).build()
}
