/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.restapi.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.Objects

/**
 * The visibility of the user's profile sections.
 *
 * @param hiddenContactInfo Whether the user's contact info section is hidden.
 * @param hiddenLinks Whether the user's links section is hidden.
 * @param hiddenInterests Whether the user's interests section is hidden.
 * @param hiddenWallet Whether the user's wallet section is hidden.
 * @param hiddenPhotos Whether the user's photo gallery section is hidden.
 * @param hiddenVerifiedAccounts Whether the user's verified accounts section is hidden.
 */
@JsonClass(generateAdapter = true)
public class ProfileSectionVisibility internal constructor(
    // Whether the user's contact info section is hidden.
    @Json(name = "hidden_contact_info")
    public val hiddenContactInfo: kotlin.Boolean? = null,
    // Whether the user's links section is hidden.
    @Json(name = "hidden_links")
    public val hiddenLinks: kotlin.Boolean? = null,
    // Whether the user's interests section is hidden.
    @Json(name = "hidden_interests")
    public val hiddenInterests: kotlin.Boolean? = null,
    // Whether the user's wallet section is hidden.
    @Json(name = "hidden_wallet")
    public val hiddenWallet: kotlin.Boolean? = null,
    // Whether the user's photo gallery section is hidden.
    @Json(name = "hidden_photos")
    public val hiddenPhotos: kotlin.Boolean? = null,
    // Whether the user's verified accounts section is hidden.
    @Json(name = "hidden_verified_accounts")
    public val hiddenVerifiedAccounts: kotlin.Boolean? = null,
) {
    override fun toString(): String = "ProfileSectionVisibility(hiddenContactInfo=$hiddenContactInfo, hiddenLinks=$hiddenLinks, hiddenInterests=$hiddenInterests, hiddenWallet=$hiddenWallet, hiddenPhotos=$hiddenPhotos, hiddenVerifiedAccounts=$hiddenVerifiedAccounts)"

    override fun equals(other: Any?): Boolean = other is ProfileSectionVisibility &&
        hiddenContactInfo == other.hiddenContactInfo &&
        hiddenLinks == other.hiddenLinks &&
        hiddenInterests == other.hiddenInterests &&
        hiddenWallet == other.hiddenWallet &&
        hiddenPhotos == other.hiddenPhotos &&
        hiddenVerifiedAccounts == other.hiddenVerifiedAccounts

    override fun hashCode(): Int = Objects.hash(hiddenContactInfo, hiddenLinks, hiddenInterests, hiddenWallet, hiddenPhotos, hiddenVerifiedAccounts)

    public class Builder {
        // Whether the user's contact info section is hidden.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var hiddenContactInfo: kotlin.Boolean? = null

        // Whether the user's links section is hidden.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var hiddenLinks: kotlin.Boolean? = null

        // Whether the user's interests section is hidden.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var hiddenInterests: kotlin.Boolean? = null

        // Whether the user's wallet section is hidden.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var hiddenWallet: kotlin.Boolean? = null

        // Whether the user's photo gallery section is hidden.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var hiddenPhotos: kotlin.Boolean? = null

        // Whether the user's verified accounts section is hidden.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var hiddenVerifiedAccounts: kotlin.Boolean? = null

        public fun setHiddenContactInfo(hiddenContactInfo: kotlin.Boolean?): Builder = apply { this.hiddenContactInfo = hiddenContactInfo }

        public fun setHiddenLinks(hiddenLinks: kotlin.Boolean?): Builder = apply { this.hiddenLinks = hiddenLinks }

        public fun setHiddenInterests(hiddenInterests: kotlin.Boolean?): Builder = apply { this.hiddenInterests = hiddenInterests }

        public fun setHiddenWallet(hiddenWallet: kotlin.Boolean?): Builder = apply { this.hiddenWallet = hiddenWallet }

        public fun setHiddenPhotos(hiddenPhotos: kotlin.Boolean?): Builder = apply { this.hiddenPhotos = hiddenPhotos }

        public fun setHiddenVerifiedAccounts(hiddenVerifiedAccounts: kotlin.Boolean?): Builder = apply { this.hiddenVerifiedAccounts = hiddenVerifiedAccounts }

        public fun build(): ProfileSectionVisibility = ProfileSectionVisibility(hiddenContactInfo, hiddenLinks, hiddenInterests, hiddenWallet, hiddenPhotos, hiddenVerifiedAccounts)
    }
}

@JvmSynthetic // Hide from Java callers who should use Builder.
public fun ProfileSectionVisibility(initializer: ProfileSectionVisibility.Builder.() -> Unit): ProfileSectionVisibility {
    return ProfileSectionVisibility.Builder().apply(initializer).build()
}
