/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.restapi.models

import com.google.gson.annotations.SerializedName
import java.util.Objects

/**
 * Details for selecting an avatar for an identity.
 *
 * @param avatarId The unique identifier of the avatar to be set.
 */

public class SelectAvatar private constructor(
    // The unique identifier of the avatar to be set.
    @SerializedName("avatar_id")
    public val avatarId: kotlin.String,
) {
    override fun toString(): String = "SelectAvatar(avatarId=$avatarId)"

    override fun equals(other: Any?): Boolean = other is SelectAvatar &&
        avatarId == other.avatarId

    override fun hashCode(): Int = Objects.hash(avatarId)

    public class Builder {
        // The unique identifier of the avatar to be set.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var avatarId: kotlin.String? = null

        public fun setAvatarId(avatarId: kotlin.String?): Builder = apply { this.avatarId = avatarId }

        public fun build(): SelectAvatar = SelectAvatar(avatarId!!)
    }
}

@JvmSynthetic // Hide from Java callers who should use Builder.
public fun SelectAvatar(initializer: SelectAvatar.Builder.() -> Unit): SelectAvatar {
    return SelectAvatar.Builder().apply(initializer).build()
}
