/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.restapi.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.Objects

/**
 * The subset of data available for update. Field names match the ones in `Profile`. Only the provided fields will be updated.
 *
 * @param firstName The user's first name.
 * @param lastName The user's last name.
 * @param displayName The user's display name. This is the name that is displayed on their profile.
 * @param description The about section on a user's profile.
 * @param pronunciation The phonetic pronunciation of the user's name.
 * @param pronouns The pronouns the user uses.
 * @param location The user's location.
 * @param jobTitle The user's job title.
 * @param company The user's current company's name.
 */
@JsonClass(generateAdapter = true)
public class UpdateProfileRequest internal constructor(
    // The user's first name.
    @Json(name = "first_name")
    public val firstName: kotlin.String? = null,
    // The user's last name.
    @Json(name = "last_name")
    public val lastName: kotlin.String? = null,
    // The user's display name. This is the name that is displayed on their profile.
    @Json(name = "display_name")
    public val displayName: kotlin.String? = null,
    // The about section on a user's profile.
    @Json(name = "description")
    public val description: kotlin.String? = null,
    // The phonetic pronunciation of the user's name.
    @Json(name = "pronunciation")
    public val pronunciation: kotlin.String? = null,
    // The pronouns the user uses.
    @Json(name = "pronouns")
    public val pronouns: kotlin.String? = null,
    // The user's location.
    @Json(name = "location")
    public val location: kotlin.String? = null,
    // The user's job title.
    @Json(name = "job_title")
    public val jobTitle: kotlin.String? = null,
    // The user's current company's name.
    @Json(name = "company")
    public val company: kotlin.String? = null,
) {
    override fun toString(): String = "UpdateProfileRequest(firstName=$firstName, lastName=$lastName, displayName=$displayName, description=$description, pronunciation=$pronunciation, pronouns=$pronouns, location=$location, jobTitle=$jobTitle, company=$company)"

    override fun equals(other: Any?): Boolean = other is UpdateProfileRequest &&
        firstName == other.firstName &&
        lastName == other.lastName &&
        displayName == other.displayName &&
        description == other.description &&
        pronunciation == other.pronunciation &&
        pronouns == other.pronouns &&
        location == other.location &&
        jobTitle == other.jobTitle &&
        company == other.company

    override fun hashCode(): Int = Objects.hash(firstName, lastName, displayName, description, pronunciation, pronouns, location, jobTitle, company)

    public class Builder {
        // The user's first name.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var firstName: kotlin.String? = null

        // The user's last name.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var lastName: kotlin.String? = null

        // The user's display name. This is the name that is displayed on their profile.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var displayName: kotlin.String? = null

        // The about section on a user's profile.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var description: kotlin.String? = null

        // The phonetic pronunciation of the user's name.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var pronunciation: kotlin.String? = null

        // The pronouns the user uses.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var pronouns: kotlin.String? = null

        // The user's location.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var location: kotlin.String? = null

        // The user's job title.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var jobTitle: kotlin.String? = null

        // The user's current company's name.
        @set:JvmSynthetic // Hide 'void' setter from Java
        public var company: kotlin.String? = null

        public fun setFirstName(firstName: kotlin.String?): Builder = apply { this.firstName = firstName }

        public fun setLastName(lastName: kotlin.String?): Builder = apply { this.lastName = lastName }

        public fun setDisplayName(displayName: kotlin.String?): Builder = apply { this.displayName = displayName }

        public fun setDescription(description: kotlin.String?): Builder = apply { this.description = description }

        public fun setPronunciation(pronunciation: kotlin.String?): Builder = apply { this.pronunciation = pronunciation }

        public fun setPronouns(pronouns: kotlin.String?): Builder = apply { this.pronouns = pronouns }

        public fun setLocation(location: kotlin.String?): Builder = apply { this.location = location }

        public fun setJobTitle(jobTitle: kotlin.String?): Builder = apply { this.jobTitle = jobTitle }

        public fun setCompany(company: kotlin.String?): Builder = apply { this.company = company }

        public fun build(): UpdateProfileRequest = UpdateProfileRequest(firstName, lastName, displayName, description, pronunciation, pronouns, location, jobTitle, company)
    }
}

@JvmSynthetic // Hide from Java callers who should use Builder.
public fun UpdateProfileRequest(initializer: UpdateProfileRequest.Builder.() -> Unit): UpdateProfileRequest {
    return UpdateProfileRequest.Builder().apply(initializer).build()
}
