# frozen_string_literal: true

default_platform(:android)

UI.user_error!('Please run fastlane via `bundle exec`') unless FastlaneCore::Helper.bundler?

RES_UI_DIR_PATH = File.join('gravatar-ui', 'src', 'main', 'res')
RES_QUICK_EDITOR_DIR_PATH = File.join('gravatar-quickeditor', 'src', 'main', 'res')
GLOTPRESS_UI_STRINGS_PROJECT_URL = 'https://translate.wordpress.com/projects/gravatar/gravatar-android-sdk/gravatar-ui/'
GLOTPRESS_QUICK_EDITOR_STRINGS_PROJECT_URL = 'https://translate.wordpress.com/projects/gravatar/gravatar-android-sdk/gravatar-quick-editor/'

SUPPORTED_LOCALES = [
  { glotpress: 'ar',    android: 'ar'     },
  { glotpress: 'de',    android: 'de'     },
  { glotpress: 'es',    android: 'es'     },
  { glotpress: 'fr',    android: 'fr'     },
  { glotpress: 'he',    android: 'he'     },
  { glotpress: 'id',    android: 'id'     },
  { glotpress: 'it',    android: 'it'     },
  { glotpress: 'ja',    android: 'ja'     },
  { glotpress: 'ko',    android: 'ko'     },
  { glotpress: 'nl',    android: 'nl'     },
  { glotpress: 'pt-br', android: 'pt-rBR' },
  { glotpress: 'ru',    android: 'ru'     },
  { glotpress: 'sv',    android: 'sv'     },
  { glotpress: 'tr',    android: 'tr'     },
  { glotpress: 'zh-cn', android: 'zh-rCN' },
  { glotpress: 'zh-tw', android: 'zh-rTW' }
].freeze

platform :android do
  # Download the latest app translations from GlotPress and update the strings.xml files accordingly.
  #
  # @example Running the lane
  #          bundle exec fastlane download_translations skip_commit:true
  #
  lane :download_translations do |skip_commit: false|
    android_download_translations(
      res_dir: RES_UI_DIR_PATH,
      glotpress_url: GLOTPRESS_UI_STRINGS_PROJECT_URL,
      locales: SUPPORTED_LOCALES,
      skip_commit: true
    )

    android_download_translations(
      res_dir: RES_QUICK_EDITOR_DIR_PATH,
      glotpress_url: GLOTPRESS_QUICK_EDITOR_STRINGS_PROJECT_URL,
      locales: SUPPORTED_LOCALES,
      skip_commit: true
    )

    next if skip_commit

    strings_paths = [RES_UI_DIR_PATH, RES_QUICK_EDITOR_DIR_PATH]
    git_add(path: strings_paths)
    git_commit(
      path: strings_paths,
      message: 'Update translations',
      allow_nothing_to_commit: true
    )
  end
end
