/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 * A crypto currency wallet address the user accepts.
 *
 * @param label The label for the crypto currency.
 * @param address The wallet address for the crypto currency.
 */

@Deprecated(
    "This class is deprecated and will be removed in a future release.",
    replaceWith = ReplaceWith("com.gravatar.restapi.models.CryptoWalletAddress"),
    level = DeprecationLevel.WARNING,
)
public data class CryptoWalletAddress(
    // The label for the crypto currency.
    @SerializedName("label")
    val label: kotlin.String,
    // The wallet address for the crypto currency.
    @SerializedName("address")
    val address: kotlin.String,
)
