/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param primary
 * @param `value`
 */

data class Email(
    @SerializedName("primary")
    val primary: kotlin.Boolean? = null,
    @SerializedName("value")
    val `value`: kotlin.String? = null,
)
