/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param code
 * @param message
 */

public data class Error(
    @SerializedName("code")
    val code: kotlin.Int,
    @SerializedName("message")
    val message: kotlin.String,
)
