/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 * A gallery image a user has uploaded.
 *
 * @param url The URL to the image.
 */

public data class GalleryImage(
    // The URL to the image.
    @SerializedName("url")
    val url: java.net.URI,
)
