/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 * An interest the user has added to their profile.
 *
 * @param id The unique identifier for the interest.
 * @param name The name of the interest.
 */

public data class Interest(
    // The unique identifier for the interest.
    @SerializedName("id")
    val id: kotlin.Int,
    // The name of the interest.
    @SerializedName("name")
    val name: kotlin.String,
)
