/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 * A link the user has added to their profile.
 *
 * @param label The label for the link.
 * @param url The URL to the link.
 */

public data class Link(
    // The label for the link.
    @SerializedName("label")
    val label: kotlin.String,
    // The URL to the link.
    @SerializedName("url")
    val url: java.net.URI,
)
