/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 * The user's public payment information. This is only provided in authenticated API requests.
 *
 * @param links A list of payment URLs the user has added to their profile.
 * @param cryptoWallets A list of crypto currencies the user accepts.
 */

public data class ProfilePayments(
    // A list of payment URLs the user has added to their profile.
    @SerializedName("links")
    val links: kotlin.collections.List<Link>,
    // A list of crypto currencies the user accepts.
    @SerializedName("crypto_wallets")
    val cryptoWallets: kotlin.collections.List<CryptoWalletAddress>,
)
