/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 * The user's contact information. This is only available if the user has chosen to make it public. This is only provided in authenticated API requests.
 *
 * @param homePhone The user's home phone number.
 * @param workPhone The user's work phone number.
 * @param cellPhone The user's cell phone number.
 * @param email The user's email address as provided on the contact section of the profile. Might differ from their account emails.
 * @param contactForm The URL to the user's contact form.
 * @param calendar The URL to the user's calendar.
 */

@Deprecated(
    "This class is deprecated and will be removed in a future release.",
    replaceWith = ReplaceWith("com.gravatar.restapi.models.ProfileContactInfo"),
    level = DeprecationLevel.WARNING,
)
public data class ProfileContactInfo(
    // The user's home phone number.
    @SerializedName("home_phone")
    val homePhone: kotlin.String? = null,
    // The user's work phone number.
    @SerializedName("work_phone")
    val workPhone: kotlin.String? = null,
    // The user's cell phone number.
    @SerializedName("cell_phone")
    val cellPhone: kotlin.String? = null,
    // The user's email address as provided on the contact section of the profile. Might differ from their account emails.
    @SerializedName("email")
    val email: kotlin.String? = null,
    // The URL to the user's contact form.
    @SerializedName("contact_form")
    val contactForm: java.net.URI? = null,
    // The URL to the user's calendar.
    @SerializedName("calendar")
    val calendar: java.net.URI? = null,
)
