/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 * A user's profile information.
 *
 * @param hash The SHA256 hash of the user's primary email address.
 * @param displayName The user's display name. This is the name that is displayed on their profile.
 * @param profileUrl The full URL for the user's profile.
 * @param avatarUrl The URL for the user's avatar image if it has been set.
 * @param avatarAltText The alt text for the user's avatar image if it has been set.
 * @param location The user's location.
 * @param description The about section on a user's profile.
 * @param jobTitle The user's job title.
 * @param company The user's current company's name.
 * @param verifiedAccounts A list of verified accounts the user has added to their profile. This is limited to a max of 4 in unauthenticated requests.
 * @param pronunciation The phonetic pronunciation of the user's name.
 * @param pronouns The pronouns the user uses.
 * @param links A list of links the user has added to their profile. This is only provided in authenticated API requests.
 * @param payments
 * @param contactInfo
 * @param gallery Additional images a user has uploaded. This is only provided in authenticated API requests.
 * @param numberVerifiedAccounts The number of verified accounts the user has added to their profile. This count includes verified accounts the user is hiding from their profile. This is only provided in authenticated API requests.
 * @param lastProfileEdit The date and time (UTC) the user last edited their profile. This is only provided in authenticated API requests.
 * @param registrationDate The date the user registered their account. This is only provided in authenticated API requests.
 */

@Deprecated(
    "This class is deprecated and will be removed in a future release.",
    replaceWith = ReplaceWith("com.gravatar.restapi.models.Profile"),
    level = DeprecationLevel.WARNING,
)
public data class Profile(
    // The SHA256 hash of the user's primary email address.
    @SerializedName("hash")
    val hash: kotlin.String,
    // The user's display name. This is the name that is displayed on their profile.
    @SerializedName("display_name")
    val displayName: kotlin.String,
    // The full URL for the user's profile.
    @SerializedName("profile_url")
    val profileUrl: java.net.URI,
    // The URL for the user's avatar image if it has been set.
    @SerializedName("avatar_url")
    val avatarUrl: java.net.URI,
    // The alt text for the user's avatar image if it has been set.
    @SerializedName("avatar_alt_text")
    val avatarAltText: kotlin.String,
    // The user's location.
    @SerializedName("location")
    val location: kotlin.String,
    // The about section on a user's profile.
    @SerializedName("description")
    val description: kotlin.String,
    // The user's job title.
    @SerializedName("job_title")
    val jobTitle: kotlin.String,
    // The user's current company's name.
    @SerializedName("company")
    val company: kotlin.String,
    // A list of verified accounts the user has added to their profile. This is limited to a max of 4 in unauthenticated requests.
    @SerializedName("verified_accounts")
    val verifiedAccounts: kotlin.collections.List<VerifiedAccount>,
    // The phonetic pronunciation of the user's name.
    @SerializedName("pronunciation")
    val pronunciation: kotlin.String,
    // The pronouns the user uses.
    @SerializedName("pronouns")
    val pronouns: kotlin.String,
    // A list of links the user has added to their profile. This is only provided in authenticated API requests.
    @SerializedName("links")
    val links: kotlin.collections.List<Link>? = null,
    @SerializedName("payments")
    val payments: ProfilePayments? = null,
    @SerializedName("contact_info")
    val contactInfo: ProfileContactInfo? = null,
    // Additional images a user has uploaded. This is only provided in authenticated API requests.
    @SerializedName("gallery")
    val gallery: kotlin.collections.List<GalleryImage>? = null,
    // The number of verified accounts the user has added to their profile. This count includes verified accounts the user is hiding from their profile. This is only provided in authenticated API requests.
    @SerializedName("number_verified_accounts")
    val numberVerifiedAccounts: kotlin.Int? = null,
    // The date and time (UTC) the user last edited their profile. This is only provided in authenticated API requests.
    @SerializedName("last_profile_edit")
    val lastProfileEdit: java.time.Instant? = null,
    // The date the user registered their account. This is only provided in authenticated API requests.
    @SerializedName("registration_date")
    val registrationDate: java.time.Instant? = null,
)
