/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param entry
 */

public data class UserProfiles(
    @SerializedName("entry")
    val entry: kotlin.collections.List<UserProfile>,
)
