/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param entry
 */

data class UserProfiles(
    @SerializedName("entry")
    val entry: kotlin.collections.List<UserProfile>,
)
