/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.models

import com.google.gson.annotations.SerializedName

/**
 * A verified account on a user's profile.
 *
 * @param serviceType The type of the service.
 * @param serviceLabel The name of the service.
 * @param serviceIcon The URL to the service's icon.
 * @param url The URL to the user's profile on the service.
 */

@Deprecated(
    "This class is deprecated and will be removed in a future release.",
    replaceWith = ReplaceWith("com.gravatar.restapi.models.VerifiedAccount"),
    level = DeprecationLevel.WARNING,
)
public data class VerifiedAccount(
    // The type of the service.
    @SerializedName("service_type")
    val serviceType: kotlin.String,
    // The name of the service.
    @SerializedName("service_label")
    val serviceLabel: kotlin.String,
    // The URL to the service's icon.
    @SerializedName("service_icon")
    val serviceIcon: java.net.URI,
    // The URL to the user's profile on the service.
    @SerializedName("url")
    val url: java.net.URI,
)
