/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.api.apis

import com.gravatar.api.models.Profile
import retrofit2.Response
import retrofit2.http.GET
import retrofit2.http.Path

@Deprecated(
    "This class is deprecated and will be removed in a future release.",
    replaceWith = ReplaceWith("com.gravatar.restapi.apis.ProfilesApi"),
    level = DeprecationLevel.WARNING,
)
internal interface ProfilesApi {
    /**
     * Get profile by identifier
     * Returns a profile by the given identifier.
     * Responses:
     *  - 200: Successful response
     *  - 404: Profile not found
     *  - 429: Rate limit exceeded
     *  - 500: Internal server error
     *
     * @param profileIdentifier This can either be an SHA256 hash of an email address or profile URL slug.
     * @return [Profile]
     */
    @GET("profiles/{profileIdentifier}")
    suspend fun getProfileById(
        @Path("profileIdentifier") profileIdentifier: kotlin.String,
    ): Response<Profile>
}
